{{- if .Values.trustAddon.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-addon-placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-addon-placeholder
  template:
    metadata:
      labels:
        app: trust-addon-placeholder
    spec:
      containers:
      - name: trust-addon-placeholder
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
{{- end }}
